version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "15:10"
    timezone: America/Sao_Paulo
  labels:
  - automerge

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "15:10"
    timezone: America/Sao_Paulo
  labels:
  - automerge

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "15:10"
    timezone: America/Sao_Paulo
  labels:
  - automerge
