name: ci
on:
  pull_request:
    types: [labeled]
  push:
    branches: [master]

jobs:
  ci:
    if: ${{ contains(github.event.label.name, 'run-ci') || github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Running CI aaaa"
